version: '3.3'

services:
  labdb1:
    image: kgsvc:latest
    volumes:
      - app_data:/app
      - nginx_conf:/etc/nginx/conf.d/
    ports:
      - "8080:80"
    restart: always

volumes:
  app_data:
    driver_opts:
      type: none
      device: YOUR_WEBSVC_FOLDER/app
      o: bind

  nginx_conf:
    driver_opts:
      type: none
      device: YOUR_WEBSVC_FOLDER/nginx_setting
      o: bind
